#!/usr/bin/env python

import sys
import rospy
import cv2
import numpy as np
from cv_bridge import CvBridge, CvBridgeError
from face_recognition_ros_wrapper.srv import *

def recognize_faces_client(image):
    rospy.wait_for_service('recognize_faces2')
    try:
        recognize_faces2 = rospy.ServiceProxy('recognize_faces2', RecognizeFaces2)
        resp1 = recognize_faces2(image)
        return resp1.recognized_person
    except rospy.ServiceException as e:
        print("Service call failed: " + str(e))

def usage():
    return sys.argv[0] + "[image]"

if __name__ == "__main__":
    if len(sys.argv) == 2:
        image_path = str(sys.argv[1])
    else:
        print(usage())
        sys.exit(1)
    print("Requesting for image ")

    image_cv = cv2.imread(image_path)
    image = CvBridge().cv2_to_imgmsg(image_cv, "bgr8")

    # cv2.imshow('image_client',image_cv)
    # cv2.waitKey(0)
    # cv2.destroyAllWindows()
    
    print("Response: " + str(recognize_faces_client(image)))