#!/usr/bin/env python

from face_recognition_ros_wrapper.srv import RecognizeFacesImage, RecognizeFacesImageResponse
import rospy
import cv2
import face_recognition
import pickle

import inspect
import os
from cv_bridge import CvBridge, CvBridgeError
from sensor_msgs.msg import *


def handle_recognize_faces(req):
    
    camera_image = rospy.wait_for_message("/webcam/image_raw", Image)

    name = "Unknown" 
    names = []
    #image = cv2.imread(req.image_path)
    try:
        image = CvBridge().imgmsg_to_cv2(camera_image, "bgr8")
    except CvBridgeError as e:
        print(e)
    # cv2.imshow('image_server',image)
    # cv2.waitKey(0)
    # cv2.destroyAllWindows()

    # rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    rgb = image
    
    # cv2.imshow('image_rgb',rgb)
    # cv2.waitKey(0)
    # cv2.destroyAllWindows()

    face_encodings_file = rospy.get_param("face_encodings_location")
    
    X, y = pickle.loads(open(face_encodings_file, "rb").read())
    
    #print("Detecting faces in image: " + req.image_path)

    boxes = face_recognition.face_locations(rgb, model='hog')
    if not boxes:
        return RecognizeFacesImageResponse(name)
    
    # detect all of the faces' encodings
    encodings = face_recognition.face_encodings(rgb, boxes)
    # go through all of the faces
    for encoding in encodings:
        matches = face_recognition.compare_faces(X, encoding)
        if True in matches:
            matchedIdxs = [i for (i, b) in enumerate(matches) if b]
            counts = {}
            for i in matchedIdxs:
                name = y[i]
                counts[name] = counts.get(name, 0) + 1        
            name = max(counts, key=counts.get)
        names.append(name)
    print(names)
    
    return RecognizeFacesImageResponse(names)

def recognize_faces_server_image():
    rospy.init_node("recognize_faces_server_image")
    s = rospy.Service('recognize_faces_image', RecognizeFacesImage, handle_recognize_faces)
    print("Ready to recognize faces")
    rospy.spin()


if __name__ == "__main__":
    recognize_faces_server_image()



# def main(argv):
#     rospy.init_node('object_detection_server')
#     ObjectDetectionServer()

# if __name__ == '__main__':
#     main(sys.argv)
